FROM python:2.7

ADD ./src /app/src

ADD requirements.txt /app/requirements.txt
ADD get_block_data.py /app/get_block_data.py

workdir /app/

RUN pip install -r requirements.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com


ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

workdir /app/

